export const NOTIFICATION_SUB_CATEGORIES = {
  LOGIN_SUCCEED: 111,
  LOGIN_FAILED: 112,
  SIGNUP_SUCCEED: 113,
  USER_VERIFICATION_REQUESTED: 121,
  USER_VERIFICATION_VERIFIED: 122,
  USER_VERIFICATION_FAILED: 123,
  TICKET_REGISTERED: 211,
  TICKET_ANSWERED: 212,
};
